name:                rabbitmq
version:             0.1.0.0
github:              "githubuser/rabbitmq"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rabbitmq#readme>
default-extensions:   GHC2021,ImportQualifiedPost, BangPatterns, NamedFieldPuns, ScopedTypeVariables, NoMonomorphismRestriction, OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- transformers
- async
- bytestring
- text
- http-client
- http-conduit
- text
- stm
- directory
- time
- aeson
- HUnit
- network
- vector
- ghc-prim
- atomic-primops
- unix 
- websockets
- unliftio
- regex-pcre
- regex-base
- random
- katip
- parallel
- deepseq
- extra
- binary
- data-binary-ieee754
- bitvec
- hspec
library:
  source-dirs: src

executables:
  rabbitmq-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  #  - -Wall
    dependencies:
    - rabbitmq

tests:
  rabbitmq-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rabbitmq
    - hspec